[package]
name = "pyramid_solitaire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
termion = "2.0.1"
chrono = "0.4"